name: ScanNgo-admin-ui-build-deploy-pipeline

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create config file
      run: |
        touch .env
        echo "REACT_APP_JWT_SECRET=${{ secrets.jwt_secret }}" >> .env

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: ECR push and ECS deploy
      uses: jaroldwong/ecr-push-and-ecs-deploy@v1
      with:
        ecr-registry: ${{ steps.login-ecr.outputs.registry }}
        ecr-repository: scanngo-admin-ui
        ecs-cluster: scanngo-new-vpc-cluster
        ecs-service: scanngo-admin-ui
